train:
  _target_: mil.data.camelyon16.Camelyon16Dataset
  cache_dir: /data/camelyon16_preprocess/cache
  train: true
  max_patches_per_bag: 6000
test:
  _target_: ${dataset.train._target_}
  cache_dir: ${dataset.train.cache_dir}
  train: false
  reference_csv_file: /data/camelyon16_preprocess/testing/reference.csv
  max_patches_per_bag: ${dataset.train.max_patches_per_bag}
