train:
  # _target_: mil.data.mnist.MNISTCollage
  bag_label_computer: # how to compute the bag label
    _target_: mil.data.mnist.TargetNumbersBagLabelComputer
    target_numbers: ${settings.mnist.target_numbers}
  num_digits: 10 # sample from all 10 MNIST digits
  min_bag_size: 2 # minimum bag length
  mean_bag_size: 10 # mean bag length
  var_bag_size: 2 # variance of bag length
  num_bags: 300 # number of bags
  seed: 1
  train: true
test:
  # _target_: mil.data.mnist.MNISTCollage
  bag_label_computer: ${dataset.train.bag_label_computer}
  num_digits: ${dataset.train.num_digits}
  min_bag_size: ${dataset.train.min_bag_size}
  mean_bag_size: ${dataset.train.mean_bag_size}
  var_bag_size: ${dataset.train.var_bag_size}
  num_bags: 100
  seed: 1
  train: false
