# @package _global_
defaults:
  - _default.yaml
  - /model: discrete_rel_pos_self_attention
  - _self_

name: discrete_rel_pos_self_attention
settings:
  agg: max
  hidden_dim: 10
optimizer:
  lr: .0001
  weight_decay: .1
