# @package _global_
defaults:
  - _default.yaml
  - /model: distance_aware_self_attention
  - _self_

name: distance_aware_self_attention
settings:
  agg: max
  hidden_dim: 10
optimizer:
  lr: .001
  weight_decay: .01
