# @package _global_
defaults:
  - _default.yaml
  - /model: self_attention_fourier_pe
  - _self_

name: self_attention_fourier_pe
settings:
  agg: max
  hidden_dim: 15
optimizer:
  lr: .001
  weight_decay: .001
