# @package _global_
defaults:
  - _default.yaml
  - /model: self_attention_axial_pe
  - _self_

name: self_attention_axial_pe
settings:
  agg: max
  hidden_dim: 15
optimizer:
  lr: .0001
  weight_decay: .1
