defaults:
  - _self_
  - dataset@dataset: mnist_collage
  - feature_extractor@model.feature_extractor: mnist

settings:
  mnist:
    target_numbers: [0, 1]
    dist_predicate: "lambda dist: dist < 50"
  feature_size: 32
  hidden_dim: 10
  output_size: ${settings.feature_size}
  agg: max
  self_attention:
    num_heads: 1
  gnn:
    num_layers: 2
    special_loss: ''

name: experiment
seed: # leave empty to use random seed
dataset: # will be overwritten
model:
  _target_: mil.models.MILModel
  feature_extractor: # will be overwritten
  pooler:
    _target_: torch_geometric.nn.Sequential
    input_args: "x, edge_index, edge_attr"
    modules:
      - [
          { _target_: mil.utils.layers.Aggregate, agg: "${settings.agg}" },
          "x -> x",
        ]
  classifier:
    _target_: mil.utils.layers.Classifier
    feature_size: ${settings.output_size}
save_epoch_freq: 1
num_epochs: 50
optimizer:
  _target_: torch.optim.AdamW
  lr: 0.001
  weight_decay: 0.01
device: cpu
wandb_id: # will be populated during training
