# @package _global_
model:
  pooler:
    modules:
      - [
          {
            _target_: mil.models.abmil.WeightedAverageAttention,
            feature_size: "${settings.feature_size}",
            hidden_dim: "${settings.hidden_dim}",
          },
          "x -> x",
        ]
      - [{ _target_: mil.utils.layers.Aggregate, agg: "sum" }, "x -> x"]
