_target_: dasmil.train.models.DasMIL
d_features: ${settings.feature_dim}
hidden_dim: 512
targets: ${dataset.targets}

mha:
  _partial_: true
  _target_: dasmil.train.models.distance_aware_attention.DistanceAwareMultiheadAttention