# @package _global_
model:
  pooler:
    modules:
      - [
          {
            _target_: mil.models.distance_aware_self_attention.MultiHeadDistanceAwareSelfAttention,
            feature_size: "${settings.feature_size}",
            output_size: "${settings.output_size}",
            hidden_dim: "${settings.hidden_dim}",
            num_heads: "${settings.self_attention.num_heads}",
            continuous: true,
            num_embeddings: "${settings.self_attention.relative.num_embeddings}",
            embed_keys: "${settings.self_attention.relative.embed_keys}",
            embed_queries: "${settings.self_attention.relative.embed_queries}",
            embed_values: "${settings.self_attention.relative.embed_values}",
            do_term3: "${settings.self_attention.relative.do_term3}",
            trainable_embeddings: "${settings.self_attention.relative.trainable_embeddings}",
          },
          "x, edge_index, edge_attr -> x",
        ]
      - [
          { _target_: mil.utils.layers.Aggregate, agg: "${settings.agg}" },
          "x -> x",
        ]
settings:
  self_attention:
    relative:
      num_embeddings: 2