# @package _global_
model:
  pooler:
    modules:
      - [
          {
            _target_: mil.models.gnn.GNN,
            feature_size: "${settings.feature_size}",
            hidden_dim: "${settings.hidden_dim}",
            layer: { _target_: torch_geometric.nn.GATConv, _partial_: true },
            num_layers: "${settings.gnn.num_layers}",
          },
          "x, edge_index, edge_attr -> x",
        ]
settings:
  gnn:
    special_loss: true # TODO: remove?
