# @package _global_
model:
  pooler:
    modules:
      - [
          {
            _target_: mil.gnn.GNN,
            hidden_dim: "${settings.hidden_dim}",
            layer: { _target_: torch_geometric.nn.GATConv, _partial_: true },
          },
          "x -> x",
        ]
