# @package _global_
defaults:
  - _self_
  - override /classifier@model.classifier: identity # ILRA already does the classification

model:
  pooler:
    modules:
      - [
          {
            _target_: mil.models.ilra.ILRA,
            feat_dim: "${settings.feature_size}",
          },
          "x -> x",
        ]
