# @package _global_
defaults:
  - _self_
  - override /classifier@model.classifier: identity # Set Transformer already does the classification

model:
  pooler:
    modules:
      - [
          {
            _target_: mil.models.set_transformer.InducedSetTransformer,
            dim_input: "${settings.feature_size}",
            num_outputs: 1,
            dim_output: 1,
            dim_hidden: "${settings.hidden_dim}",
            num_heads: "${settings.self_attention.num_heads}",
            num_inds: 32,
          },
          "x -> x",
        ]
