# @package _global_
model:
  pooler:
    modules:
      - [
          {
            _target_: mil.models.gnn.GNN,
            feature_size: "${settings.feature_size}",
            hidden_dim: "${settings.hidden_dim}",
          },
          "x, edge_index, edge_attr -> x",
        ]

settings:
  output_size: ${settings.hidden_dim}
  gnn:
    special_loss: "with_deep_supervision"
