# Lookahead optimizer for TransMIL (all values are set according to their paper)
_target_: mil.optim.lookahead.Lookahead
base_optimizer:
  _target_: mil.optim.radam.RAdam
  _partial_: true
  lr: 2e-4
  weight_decay: 1e-5
