# @package _global_
defaults:
  - _default.yaml
  - /model: discrete_rel_pos_self_attention
  - override /optimizer@optimizer: transmil_lookahead
  - _self_

name: discrete_rel_pos_self_attention
settings:
  agg: max
  hidden_dim: 10
  output_size: 16
  self_attention:
    relative:
      do_term3: true
optimizer:
  base_optimizer:
    lr: .001
    weight_decay: 1e-05