# @package _global_
defaults:
  - _default.yaml
  - /model: ilra
  - _self_

# https://github.com/jinxixiang/low_rank_wsi/blob/main/mil/configs/config_ilra_camelyon16_imagenet.yaml

name: ilra
# settings:
optimizer:
  _target_: torch.optim.Adam
  lr: 0.0001
  amsgrad: False
lr_scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: ${num_epochs}
  last_epoch: -1