# @package _global_
defaults:
  - _default.yaml
  - /model: ilra
  - override /optimizer@optimizer: transmil_lookahead
  - _self_

# https://github.com/jinxixiang/low_rank_wsi/blob/main/mil/configs/config_ilra_camelyon16_imagenet.yaml

name: ilra_ourparams
# settings:
optimizer:
  base_optimizer:
    lr: .001
    weight_decay: 1e-05