# @package _global_
defaults:
  - _default.yaml
  - /model: just_pool
  - override /optimizer@optimizer: transmil_lookahead
  - _self_

name: just_pool
settings:
  agg: max
  hidden_dim: 10
  output_size: "${settings.feature_size}"
optimizer:
  base_optimizer:
    lr: .001
    weight_decay: 1e-05
