# @package _global_
defaults:
  - _default.yaml
  - /model: distance_aware_self_attention
  - _self_

name: distance_aware_self_attention_embedkq_noterm3
settings:
  agg: max
  hidden_dim: 10
  self_attention:
    relative:
      embed_keys: true
      embed_queries: true
      embed_values: false
      do_term3: false
optimizer:
  lr: .001
  weight_decay: .01
