# @package _global_
defaults:
  - _default.yaml
  - /model: distance_aware_self_attention
  - _self_

name: distance_aware_self_attention_fixedembed
settings:
  agg: max
  hidden_dim: 10
  self_attention:
    relative:
      trainable_embeddings: false
optimizer:
  lr: .001
  weight_decay: .01
